name: NPM Audit Fix Run

on:
  workflow_dispatch:
    inputs:
      package_manager:
        description: "Specify package manager (npm or yarn)"
        required: false
        default: "yarn"
      base_branch:
        description: "Specify a base branch"
        required: false
        default: "main"
      script:
        description: "Specify the build script to run"
        required: false
        type: string
        default: "yarn all"
  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      package_manager: "yarn"
      base_branch: ${{ inputs.base_branch || 'main' }}
      script: ${{ inputs.script || 'yarn all' }}


permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write
